### ISSUE TITLE
make an itch.io page for the game and build

### ISSUE THREAD

**Issue by antisunshine** [antisunshine/catgame#11]
The current publish to unityplay is dodgy and I'm unable to upload it there anymore.
Random 505 error that seems to be a known problem for this type of release type.

Convert build into something we can slap on itch.io

**Comment by zennator** [comment]
Done! I will leave this task open if there comes new updates.

**Comment by antisunshine** [comment]
Link?

**Comment by zennator** [comment]
https://torzy.itch.io/catgame

**Comment by zennator** [comment]
https://itch.io/t/2796312/catgame

**Comment by zennator** [comment]
Done https://torzy.itch.io/catgame
