### ISSUE TITLE
Add a timer for the game

### ISSUE THREAD

**Issue by antisunshine** [antisunshine/catgame#12]
Add a timer. Maybe 60s to spawn enemies and kill them until it displays a scoreboard and asks if you want to go again or go to the main menu.

**Comment by zennator** [comment]
Can't find the right text object. Script is this:
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;


public class Timer : MonoBehaviour

{
    public float timeValue = 90;
    public Text timeText;


    void Update()

    {
        if (timeValue > 0)
        {
            timeValue -= Time.deltaTime;
        }
        else
        {
            timeValue += 0;
        }
    }
    void DisplayTime(float timeToDisplay)
    {
        if (timeToDisplay < 0)
        {
            timeToDisplay = 0;
        }

        float minutes = Mathf.FloorToInt(timeToDisplay /60);
        float seconds = Mathf.FloorToInt(timeToDisplay % 60);

        timeText.text = string.Format("{0:00}:{1:00}", minutes, seconds);
    }
}

**Comment by antisunshine** [comment]
Oh and add 
using TMPro;

**Comment by antisunshine** [comment]
Timer is now done and game makes a game over screen when time is up.
